"""Seed dev-mode historical load curves for the SLURM advisor.

Background: the slurm_availability tool's slot ranker uses a 24-element
hour-of-day load curve to score time slots. Real curves come from running
`scheduling/features.py` against 30 days of sacct dumps on a production
node. On a developer's laptop we don't have that data, so the calendar
card shows a red "Pre-validation: synthetic curve" banner.

This script bridges the gap: it writes synthetic-but-shaped
`data/features/partitions/<partition>.json` files for every GPU partition
in `betty_cluster.yaml`, using configurable hour-of-day shapes that mimic
the empirical patterns we expect (low overnight, high mid-day). Dev
environments can then run the advisor end-to-end with `load_curve_kind:
"historical"` rendering, which exercises the file-loading path that
production will use.

Usage:
    python -m slurm_advisor.scripts.seed_dev_load_curves
    python -m slurm_advisor.scripts.seed_dev_load_curves --shape flat
    python -m slurm_advisor.scripts.seed_dev_load_curves --shape nighttime-heavy
    python -m slurm_advisor.scripts.seed_dev_load_curves --output /tmp/features

Note: this is for DEVELOPMENT and TESTING only. Production uses
scheduling/features.py output, never this script. The generated files are
labeled with `"_dev_seed_marker": true` so review tooling can flag them
if they appear on a production node.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Dict, List

from slurm_advisor.policy import Policy

# Hour-of-day shapes (24 elements, sums roughly proportional to "load weight").
# The advisor normalizes to peak so absolute scale doesn't matter — the
# pattern is what flips synthetic curves to historical.
SHAPES: Dict[str, List[int]] = {
    # Default: typical academic cluster — quiet overnight, busy mid-day.
    "academic": [
        20, 15, 10, 10, 10, 15,    # 00–05
        25, 40, 60, 75, 85, 90,    # 06–11
        90, 90, 85, 80, 80, 75,    # 12–17
        70, 60, 50, 40, 30, 25,    # 18–23
    ],
    # Flat: every hour equally loaded; useful for testing "no time-of-day
    # signal" scenarios.
    "flat": [50] * 24,
    # Nighttime-heavy: simulates a cluster used by international collabs
    # whose timezones overlap with our overnight.
    "nighttime-heavy": [
        80, 85, 90, 90, 85, 80,    # 00–05 BUSY
        70, 60, 50, 40, 35, 30,    # 06–11 quiet morning
        30, 35, 40, 50, 55, 60,    # 12–17 ramp
        70, 75, 80, 80, 80, 80,    # 18–23 busy evening
    ],
    # Weekend-quiet: less variation, lower overall.
    "weekend-quiet": [
        15, 12, 10, 10, 10, 12,
        15, 18, 22, 25, 28, 30,
        30, 30, 28, 26, 24, 22,
        20, 18, 16, 14, 13, 14,
    ],
}


def write_curve_for_partition(
    output_dir: Path,
    partition_name: str,
    counts_by_hour: List[int],
) -> Path:
    """Write a single partition's features file in the format the loader expects.

    The schema mirrors what `scheduling/features.py` writes — `availability.py`
    reads `submit_count_by_hour` to build the load curve. Adding extra
    fields like `_dev_seed_marker` is fine; the loader ignores them.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"{partition_name}.json"
    payload = {
        "_dev_seed_marker": True,
        "_dev_seed_note": (
            "Generated by slurm_advisor/scripts/seed_dev_load_curves.py for "
            "DEVELOPMENT use only. Production must overwrite this file with "
            "output from scheduling/features.py against real sacct data."
        ),
        "partition": partition_name,
        "submit_count_by_hour": counts_by_hour,
    }
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return path


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="seed_dev_load_curves")
    parser.add_argument(
        "--shape",
        choices=sorted(SHAPES.keys()),
        default="academic",
        help="Hour-of-day shape to apply to every partition (default: academic).",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output directory. Default: betty-ai/data/features/partitions/.",
    )
    parser.add_argument(
        "--partition",
        default=None,
        help="Apply only to a specific partition (default: all GPU partitions).",
    )
    args = parser.parse_args(argv)

    counts = SHAPES[args.shape]
    if args.output:
        out = Path(args.output)
    else:
        # Resolve relative to the betty-ai package (parent of slurm_advisor/)
        here = Path(__file__).resolve()
        # …/betty-ai/slurm_advisor/scripts/seed_dev_load_curves.py → …/betty-ai/data/features/partitions
        betty_ai = here.parent.parent.parent
        out = betty_ai / "data" / "features" / "partitions"

    policy = Policy.load()
    targets = policy.gpu_partitions()
    if args.partition:
        targets = [p for p in targets if p.name == args.partition]
        if not targets:
            print(f"unknown partition: {args.partition}", file=sys.stderr)
            return 2

    written: List[Path] = []
    for p in targets:
        path = write_curve_for_partition(out, p.name, counts)
        written.append(path)
        print(f"[seed] wrote {path}  shape={args.shape}  peak={max(counts)}")

    print(f"[seed] done. {len(written)} file(s) written. "
          "Run slurm_availability now to see load_curve_kind=historical.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
